version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
    groups:
      go-modules:
        patterns: ["*"]

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
