"""Self-test for the Cargo lockfile sync driver (tools/sync_cargo_lock_version.py).

The driver is what keeps a ``rust-v*`` tag publishable: it writes the freshly
bumped ``rust/Cargo.toml`` version into ``rust/Cargo.lock`` from within
python-semantic-release's ``build_command``, before the release commit is made.
Get it wrong and the tag points at a tree ``cargo publish`` rejects — the exact
failure that kept rs-identity-model 0.1.0 through 0.3.1 off crates.io — so its
parsing and its ``--check`` guard are pinned here.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest


_REPO_ROOT = Path(__file__).resolve().parents[2]
_DRIVER = _REPO_ROOT / "tools" / "sync_cargo_lock_version.py"
_spec = importlib.util.spec_from_file_location("sync_cargo_lock_version", _DRIVER)
assert _spec is not None
assert _spec.loader is not None
sync_cargo_lock_version = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sync_cargo_lock_version)

read_manifest_version = sync_cargo_lock_version.read_manifest_version
lock_version = sync_cargo_lock_version.lock_version
sync_lock = sync_cargo_lock_version.sync_lock
SyncError = sync_cargo_lock_version.SyncError
main = sync_cargo_lock_version.main
EXIT_OK = sync_cargo_lock_version.EXIT_OK
EXIT_DRIFT = sync_cargo_lock_version.EXIT_DRIFT
EXIT_MALFORMED = sync_cargo_lock_version.EXIT_MALFORMED

CRATE = "rs-identity-model"

MANIFEST = """\
[package]
name = "rs-identity-model"
version = "0.3.1"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", default-features = false }
serde = "1"

[profile.release]
version = "not-a-crate-version"
"""

# Two dependencies deliberately sit at the same version the crate is moving
# away from, so a rewrite that matches on the version string rather than the
# owning [[package]] block corrupts them visibly.
LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "aho-corasick"
version = "0.3.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "rs-identity-model"
version = "0.3.0"
dependencies = [
 "reqwest",
 "serde",
]

[[package]]
name = "serde"
version = "0.3.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"""


def _write_pair(
    tmp_path: Path, manifest: str = MANIFEST, lock: str = LOCK
) -> tuple[Path, Path]:
    manifest_path = tmp_path / "Cargo.toml"
    lock_path = tmp_path / "Cargo.lock"
    manifest_path.write_text(manifest)
    lock_path.write_text(lock)
    return manifest_path, lock_path


def _argv(manifest: Path, lock: Path, *extra: str) -> list[str]:
    return ["--manifest", str(manifest), "--lock", str(lock), *extra]


def _packages(lock_text: str) -> dict[str, str]:
    """Parse a lockfile into {crate name: version}, for whole-file assertions."""
    packages: dict[str, str] = {}
    name: str | None = None
    for raw in lock_text.splitlines():
        line = raw.strip()
        if line == "[[package]]":
            name = None
        elif line.startswith('name = "'):
            name = line.split('"')[1]
        elif line.startswith('version = "') and name is not None:
            packages[name] = line.split('"')[1]
            name = None
    return packages


class TestReadManifestVersion:
    def test_reads_the_package_version(self) -> None:
        assert read_manifest_version(MANIFEST) == "0.3.1"

    def test_ignores_versions_in_other_tables(self) -> None:
        """A `version` under [dependencies]/[profile] is not the crate's version."""
        manifest = '[dependencies]\nversion = "9.9.9"\n\n[package]\nversion = "1.2.3"\n'
        assert read_manifest_version(manifest) == "1.2.3"

    def test_tolerates_whitespace_around_the_assignment(self) -> None:
        assert read_manifest_version('[package]\n  version   =   "4.5.6"\n') == "4.5.6"

    def test_raises_when_no_package_version_exists(self) -> None:
        with pytest.raises(SyncError, match="no \\[package\\] version"):
            read_manifest_version('[dependencies]\nserde = "1"\n')


class TestLockVersion:
    def test_reads_the_crate_entry(self) -> None:
        assert lock_version(LOCK, CRATE) == "0.3.0"

    def test_reads_a_dependency_entry(self) -> None:
        assert lock_version(LOCK, "serde") == "0.3.0"

    def test_does_not_depend_on_version_following_name(self) -> None:
        """Cargo's field order is conventional, not guaranteed."""
        lock = '[[package]]\nsource = "registry+x"\nname = "rs-identity-model"\nversion = "7.0.0"\n'
        assert lock_version(lock, CRATE) == "7.0.0"

    def test_raises_for_an_absent_crate(self) -> None:
        with pytest.raises(SyncError, match="no \\[\\[package\\]\\] entry"):
            lock_version(LOCK, "nonexistent-crate")

    def test_raises_for_an_entry_without_a_version(self) -> None:
        with pytest.raises(SyncError, match="has no version"):
            lock_version('[[package]]\nname = "rs-identity-model"\n', CRATE)


class TestSyncLock:
    def test_rewrites_only_the_named_crate(self) -> None:
        assert _packages(sync_lock(LOCK, CRATE, "0.3.1")) == {
            "aho-corasick": "0.3.0",
            "rs-identity-model": "0.3.1",
            "serde": "0.3.0",
        }

    def test_leaves_every_other_line_untouched(self) -> None:
        synced = sync_lock(LOCK, CRATE, "0.3.1")
        assert synced == LOCK.replace(
            'name = "rs-identity-model"\nversion = "0.3.0"',
            'name = "rs-identity-model"\nversion = "0.3.1"',
        )

    def test_preserves_a_trailing_newline(self) -> None:
        assert sync_lock(LOCK, CRATE, "0.3.1").endswith("\n")

    def test_preserves_the_absence_of_a_trailing_newline(self) -> None:
        assert not sync_lock(LOCK.rstrip("\n"), CRATE, "0.3.1").endswith("\n")

    def test_is_idempotent(self) -> None:
        once = sync_lock(LOCK, CRATE, "0.3.1")
        assert sync_lock(once, CRATE, "0.3.1") == once


class TestCheckMode:
    def test_passes_when_versions_agree(self, tmp_path: Path) -> None:
        manifest, lock = _write_pair(tmp_path, lock=sync_lock(LOCK, CRATE, "0.3.1"))
        assert main(_argv(manifest, lock, "--check")) == EXIT_OK

    def test_fails_on_the_drift_that_broke_rust_v0_3_1(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """Manifest 0.3.1 + lock 0.3.0 — the exact shape of the broken tags."""
        manifest, lock = _write_pair(tmp_path)
        assert main(_argv(manifest, lock, "--check")) == EXIT_DRIFT
        stderr = capsys.readouterr().err
        assert "0.3.0" in stderr
        assert "0.3.1" in stderr
        assert "cargo publish" in stderr

    def test_leaves_the_lockfile_untouched(self, tmp_path: Path) -> None:
        manifest, lock = _write_pair(tmp_path)
        main(_argv(manifest, lock, "--check"))
        assert lock.read_text() == LOCK

    def test_reports_a_missing_file_distinctly_from_drift(self, tmp_path: Path) -> None:
        manifest, lock = _write_pair(tmp_path)
        lock.unlink()
        assert main(_argv(manifest, lock, "--check")) == EXIT_MALFORMED

    def test_reports_a_malformed_manifest_distinctly_from_drift(
        self, tmp_path: Path
    ) -> None:
        manifest, lock = _write_pair(tmp_path, manifest='[dependencies]\nserde = "1"\n')
        assert main(_argv(manifest, lock, "--check")) == EXIT_MALFORMED


class TestWriteMode:
    def test_syncs_the_lock_to_the_manifest(self, tmp_path: Path) -> None:
        manifest, lock = _write_pair(tmp_path)
        assert main(_argv(manifest, lock)) == EXIT_OK
        assert _packages(lock.read_text()) == {
            "aho-corasick": "0.3.0",
            "rs-identity-model": "0.3.1",
            "serde": "0.3.0",
        }

    def test_leaves_check_passing_afterwards(self, tmp_path: Path) -> None:
        manifest, lock = _write_pair(tmp_path)
        main(_argv(manifest, lock))
        assert main(_argv(manifest, lock, "--check")) == EXIT_OK

    def test_is_a_no_op_when_already_in_sync(self, tmp_path: Path) -> None:
        synced = sync_lock(LOCK, CRATE, "0.3.1")
        manifest, lock = _write_pair(tmp_path, lock=synced)
        assert main(_argv(manifest, lock)) == EXIT_OK
        assert lock.read_text() == synced

    def test_honours_an_alternate_crate_name(self, tmp_path: Path) -> None:
        manifest, lock = _write_pair(tmp_path)
        assert main(_argv(manifest, lock, "--crate", "serde")) == EXIT_OK
        assert _packages(lock.read_text())["serde"] == "0.3.1"

    def test_refuses_an_unknown_crate(self, tmp_path: Path) -> None:
        manifest, lock = _write_pair(tmp_path)
        assert (
            main(_argv(manifest, lock, "--crate", "nonexistent-crate"))
            == EXIT_MALFORMED
        )
        assert lock.read_text() == LOCK


class TestAgainstTheRealCrate:
    def test_repo_defaults_resolve_without_a_cwd_assumption(self) -> None:
        """Paths come from the driver's own location, not the caller's cwd."""
        assert (
            sync_cargo_lock_version.DEFAULT_MANIFEST
            == _REPO_ROOT / "rust" / "Cargo.toml"
        )
        assert (
            sync_cargo_lock_version.DEFAULT_LOCK == _REPO_ROOT / "rust" / "Cargo.lock"
        )

    def test_the_checked_in_lock_and_manifest_agree(self) -> None:
        """main is publishable: the release guard must be green on every commit."""
        manifest_version = read_manifest_version(
            sync_cargo_lock_version.DEFAULT_MANIFEST.read_text()
        )
        recorded = lock_version(sync_cargo_lock_version.DEFAULT_LOCK.read_text(), CRATE)
        assert recorded == manifest_version

    def test_parses_the_real_lockfile_shape(self) -> None:
        packages = _packages(sync_cargo_lock_version.DEFAULT_LOCK.read_text())
        assert packages[CRATE] == lock_version(
            sync_cargo_lock_version.DEFAULT_LOCK.read_text(), CRATE
        )
